server:
  port: 8080

spring:
  application:
    name: jwt-validator

logging:
  level:
    com.itau.jwtvalidator: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health

api:
  valid-roles: ${VALID_ROLES}
  max-name-length: ${MAX_NAME_LENGTH}